import { Package, MessageCircle, Users, Wallet, Globe, BarChart3, Store, Bot, ShoppingBag } from 'lucide-react'

export type Billing = 'monthly'|'yearly'

export const PLAN_BRANCHES = [1, 3, 10]

export const PLANS = [
  { name:'الأساسية', nameEn:'Basic', price:'99', yearlyPrice:'950', color:'#0f766e', popular:false,
    limits:['فرع واحد','3 موظفين','3 موردين'],
    limitsEn:['1 branch','3 staff','3 suppliers'],
    features:['تتبع المخزون لحظياً','صرف يومي بصلاحيات موظفين','المشتريات وإدارة الموردين','تنبيهات واتساب تلقائية','كشف الهدر','تقارير أساسية قابلة للتصدير','نسخ احتياطي يومي','دعم عبر واتساب'],
    featuresEn:['Real-time inventory tracking','Daily dispensing with staff permissions','Purchasing and supplier management','Automatic WhatsApp alerts','Waste detection','Exportable basic reports','Daily backups','Support via WhatsApp'],
    addonNote:'🧩 تقدر تفعّل ميزات إضافية اختيارية لاحقاً، كل وحدة بسعرها الخاص — مثل موظف/مورد إضافي، إدارة موظفين كاملة، إقفال الكاشير، وأدوات الذكاء الاصطناعي',
    addonNoteEn:'🧩 You can enable optional extra features later, each priced separately — like extra staff/suppliers, full HR management, cashier closing, and AI tools' },
  { name:'المتوسطة', nameEn:'Standard', price:'249', yearlyPrice:'2390', color:'#0f766e', popular:true,
    limits:['3 فروع','10 موظفين','10 موردين'],
    limitsEn:['3 branches','10 staff','10 suppliers'],
    features:['تتبع المخزون','تنبيهات واتساب','إدارة الموظفين','تقارير أساسية','إدارة الموردين','تقارير متقدمة','إقفال الكاشير اليومي','الحضور والانصراف بـGPS 📍','اقتراح الشراء الذكي 🤖','توقع نفاد المخزون 🔮','تحليل الموسمية','تحسين نقطة إعادة الطلب 🎯'],
    featuresEn:['Inventory tracking','WhatsApp alerts','Staff management','Basic reports','Supplier management','Advanced reports','Daily cashier closing','GPS attendance 📍','Smart purchase suggestions 🤖','Stock-out prediction 🔮','Seasonality analysis','Reorder point optimization 🎯'] },
  { name:'المتقدمة', nameEn:'Advanced', price:'399', yearlyPrice:'3830', color:'#0f766e', popular:false,
    limits:['10 فروع','غير محدود','غير محدود'],
    limitsEn:['10 branches','Unlimited','Unlimited'],
    features:['تتبع المخزون','تنبيهات واتساب','إدارة الموظفين','تقارير أساسية','إدارة الموردين','تقارير متقدمة','إقفال الكاشير اليومي','الحضور والانصراف بـGPS 📍','اقتراح الشراء الذكي 🤖','توقع نفاد المخزون 🔮','تحليل الموسمية','تحسين نقطة إعادة الطلب 🎯','مقارنة الفروع 🤖','المخزون الراكد 🐌','كشف الهدر الحقيقي 🗑️','دعم ذو أولوية','دعم 24/7'],
    featuresEn:['Inventory tracking','WhatsApp alerts','Staff management','Basic reports','Supplier management','Advanced reports','Daily cashier closing','GPS attendance 📍','Smart purchase suggestions 🤖','Stock-out prediction 🔮','Seasonality analysis','Reorder point optimization 🎯','Branch comparison 🤖','Stagnant inventory 🐌','Real waste detection 🗑️','Priority support','24/7 support'] },
]

export const LS: Record<string, {ar:string, en:string}> = {
  navFeatures:   { ar:'المميزات', en:'Features' },
  navPricing:    { ar:'الأسعار', en:'Pricing' },
  navFaq:        { ar:'الأسئلة', en:'FAQ' },
  navLogin:      { ar:'دخول', en:'Log in' },
  navDemo:       { ar:'اطلب عرض النظام', en:'Book a demo' },
  heroBadge:     { ar:'تجربة مجانية 14 يوماً — بدون بطاقة ائتمانية', en:'14-day free trial — no credit card required' },
  heroH1a:       { ar:'نصمّم مستقبل الإدارة الذكية', en:'We design the future of smart management' },
  heroH1b:       { ar:'لكل منشأة تطمح للنمو', en:'for every business aiming to grow' },
  heroSub:       { ar:'من المخزون والمشتريات، لصفحة عرض منتجاتك الإلكترونية، وإدارة الموظفين والفروع — كل شي بمكان واحد', en:'From inventory and purchasing, to your product showcase page, to staff and branch management — all in one place' },
  heroTry:       { ar:'جرب نظام Storely', en:'Try Storely' },
  heroStart:     { ar:'ابدأ تجربتك المجانية', en:'Start your free trial' },
  trustedBy:     { ar:'موثوق من قبل منشآت رائدة', en:'Trusted by leading businesses' },
  statStart:     { ar:'يبدأ من', en:'starting at' },
  statFree:      { ar:'مجاناً', en:'free' },
  statLangs:     { ar:'لغات', en:'languages' },
  statAlerts:    { ar:'تنبيهات', en:'alerts' },
  featuresTag:   { ar:'المميزات', en:'FEATURES' },
  featuresTitle: { ar:'كل أدوات إدارة منشأتك بمكان واحد', en:'Every tool to run your business, in one place' },
  trustTitle:    { ar:'نبني الثقة مع منشآت في كل مكان', en:'Building trust with businesses everywhere' },

  demoTitle:     { ar:'اطلب عرض النظام', en:'Book a demo' },
  demoSub:       { ar:'عبّي بياناتك وبنتواصل معك خلال ساعات عبر واتساب', en:"Fill in your details and we'll reach out within hours via WhatsApp" },
  demoFirstName: { ar:'الاسم *', en:'First name *' },
  demoLastName:  { ar:'اسم العائلة *', en:'Last name *' },
  demoPhone:     { ar:'رقم الهاتف *', en:'Phone number *' },
  demoEmail:     { ar:'البريد الإلكتروني *', en:'Email *' },
  demoBusiness:  { ar:'اسم المنشأة *', en:'Business name *' },
  demoBranches:  { ar:'عدد الفروع', en:'Number of branches' },
  demoPleaseSelect: { ar:'يرجى التحديد', en:'Please select' },
  demoAgree:     { ar:'أؤكد أني قرأت وأوافق على', en:'I confirm I have read and agree to the' },
  demoTerms:     { ar:'الشروط والأحكام', en:'Terms & Conditions' },
  demoAnd:       { ar:'و', en:'and' },
  demoPrivacy:   { ar:'سياسة الخصوصية', en:'Privacy Policy' },
  demoSending:   { ar:'جاري الإرسال...', en:'Sending...' },
  demoSubmit:    { ar:'إرسال الطلب', en:'Send request' },
  demoSideTitle: { ar:'اطلب تجربة Storely مجاناً — نظام واحد يربط كل أعمال منشأتك', en:'Request a free Storely trial — one system for your whole business' },
  demoSideSub:   { ar:'بنساعدك تختار الباقة الأنسب لمنشأتك، ونجاوب على كل أسئلتك مباشرة', en:"We'll help you pick the right plan for your business and answer all your questions directly" },

  pricingTag:    { ar:'الأسعار', en:'PRICING' },
  pricingTitle:  { ar:'باقة تناسب كل حجم منشأة', en:'A plan for every business size' },
  billMonthly:   { ar:'شهري', en:'Monthly' },
  billYearly:    { ar:'سنوي', en:'Yearly' },
  billSave:      { ar:'وفّر 20%', en:'Save 20%' },
  mostPopular:   { ar:'الأكثر شيوعاً', en:'Most popular' },
  perMonth:      { ar:'شهرياً', en:'/mo' },
  perYear:       { ar:'سنوياً', en:'/yr' },
  featuresAvail: { ar:'ميزة متاحة', en:'features included' },
  startNow:      { ar:'ابدأ الآن', en:'Start now' },

  ctaReady:      { ar:'جاهز تبدأ؟', en:'Ready to start?' },
  ctaSub:        { ar:'جرّب Storely مجاناً 14 يوماً — بدون بطاقة ائتمانية', en:'Try Storely free for 14 days — no credit card required' },
  ctaRegister:   { ar:'سجّل مجاناً الآن', en:'Sign up free now' },
  ctaContact:    { ar:'تواصل معنا', en:'Contact us' },

  faqTag:        { ar:'الأسئلة الشائعة', en:'FAQ' },
  faqTitle:      { ar:'عندك سؤال؟', en:'Got a question?' },

  footerTagline: { ar:'نظام واحد يربط كل أعمال منشأتك', en:'One system that connects your whole business' },
  footerPlatform:{ ar:'المنصة', en:'Platform' },
  footerLegal:   { ar:'قانوني', en:'Legal' },
  footerContact: { ar:'تواصل', en:'Contact' },
  footerLogin:   { ar:'تسجيل الدخول', en:'Log in' },
  footerSignup:  { ar:'إنشاء حساب', en:'Create account' },
  footerPricing: { ar:'الأسعار', en:'Pricing' },
  footerPrivacy: { ar:'سياسة الخصوصية', en:'Privacy Policy' },
  footerTerms:   { ar:'الشروط والأحكام', en:'Terms & Conditions' },
  footerSecurity:{ ar:'سياسة الأمان', en:'Security Policy' },
  footerWhatsapp:{ ar:'واتساب', en:'WhatsApp' },
  footerEmail:   { ar:'البريد الإلكتروني', en:'Email' },
  footerRights:  { ar:'جميع الحقوق محفوظة لدى Storely', en:'All rights reserved to Storely' },

  // التصميم الجديد
  navHow:        { ar:'كيف يشتغل', en:'How it works' },
  navStart:      { ar:'ابدأ مجاناً', en:'Start free' },
  heroTitleA:    { ar:'ودّع الدفاتر والإكسل،', en:'Say goodbye to notebooks and spreadsheets,' },
  heroTitleB:    { ar:'وأدر منشأتك', en:'and run your business' },
  heroTitleC:    { ar:'بهدوء', en:'calmly' },
  heroWatch:     { ar:'شوف كيف يشتغل', en:'See how it works' },
  heroPoint1:    { ar:'إعداد خلال دقائق', en:'Set up in minutes' },
  heroPoint2:    { ar:'دعم عربي عبر واتساب', en:'Arabic support on WhatsApp' },
  heroPoint3:    { ar:'بدون عقود', en:'No contracts' },
  storyTag:      { ar:'صُمم لأصحاب المنشآت', en:'Built for business owners' },
  storyTitle:    { ar:'كل صباح، تعرف وضع منشأتك في دقيقة', en:'Every morning, know where your business stands in a minute' },
  storyBody:     { ar:'ما تحتاج تكون محاسب ولا خبير أنظمة. افتح Storely مع قهوتك، وتشوف وش نقص، وش انصرف، ومين حضر من موظفينك — من أي فرع، ومن جوالك.', en:"You don't need to be an accountant. Open Storely with your coffee and see what's running low, what was used, and who showed up — from any branch, on your phone." },
  storyP1:       { ar:'مخزونك ومشترياتك وصرفك بمكان واحد', en:'Inventory, purchases and usage in one place' },
  storyP2:       { ar:'تنبيه قبل ما يخلص أي صنف', en:'An alert before anything runs out' },
  storyP3:       { ar:'موظفينك يصرفون برمز PIN بدون ما يشوفون بياناتك', en:'Staff dispense with a PIN, without seeing your data' },
  howTag:        { ar:'كيف يشتغل', en:'How it works' },
  howTitle:      { ar:'شوف Storely وهو يشتغل عنك', en:'Watch Storely work for you' },
  how1T:         { ar:'المخزون وصل الحد الأدنى؟', en:'Stock hit its minimum?' },
  how1D:         { ar:'يروح طلب التوريد للمورد على الواتساب تلقائياً، ويوصلك تأكيده أول ما يرد.', en:'A supply order goes to your supplier on WhatsApp automatically, and you get their confirmation.' },
  how2T:         { ar:'إقفال الكاشير اليومي', en:'Daily cashier closing' },
  how2D:         { ar:'المبيعات والشبكة والمسحوبات والكاش الفعلي — وأي زيادة أو عجز يوصلك فوراً.', en:'Sales, card, withdrawals and actual cash — any surplus or shortage reaches you instantly.' },
  how3T:         { ar:'النقل بين الفروع', en:'Transfers between branches' },
  how3D:         { ar:'جمّع الأصناف وانقلها دفعة وحدة، والكميات تتحدث في الفرعين.', en:'Gather items and move them in one go; both branches update.' },
  how4T:         { ar:'الحضور والانصراف', en:'Attendance' },
  how4D:         { ar:'كل موظف يسجّل حضوره برقم جواله ورمز PIN، وتشوف مين حضر ومين تأخر.', en:'Each employee checks in with their phone and PIN; see who is in and who is late.' },
  supTag:        { ar:'الموردين', en:'Suppliers' },
  supTitle:      { ar:'مورّدك صار جزء من فريقك', en:'Your supplier becomes part of your team' },
  supBody:       { ar:'لما ينقص صنف، يوصل مورّدك طلب واضح على الواتساب بالكمية والفرع. يرد بـ«تم»، وتوصلك الموافقة — بدون مكالمات ولا نسيان.', en:'When an item runs low, your supplier gets a clear WhatsApp order with quantity and branch. They reply "done" and you get the confirmation — no calls, nothing forgotten.' },
  ctaTitle:      { ar:'منشأتك تستاهل إدارة أهدأ', en:'Your business deserves calmer management' },
}

export const FAQ_ITEMS = [
  {q:'هل Storely منصة معتمدة ولها سجل تجاري؟',a:'نعم — Storely تابعة لـ «مؤسسة باسم علي خلوي لتقنية المعلومات»، مسجّلة رسمياً في وزارة التجارة السعودية بالرقم الوطني الموحد 7055023522، ونوع الكيان مؤسسة، وحالة السجل نشط. تقدر تتحقق من السجل بنفسك عبر موقع وزارة التجارة mc.gov.sa.',
   qEn:'Is Storely a registered business?',aEn:'Yes — Storely is operated by Basim Ali Khulwi Information Technology Est., officially registered with the Saudi Ministry of Commerce under unified national number 7055023522 (entity type: establishment, status: active). You can verify it yourself at mc.gov.sa.'},
  {q:'هل فيه تجربة مجانية؟',a:'نعم — 14 يوماً مجانية كاملة بدون بطاقة ائتمانية. استكشف جميع المميزات من أول يوم.',
   qEn:'Is there a free trial?',aEn:"Yes — a full 14 days free, no credit card required. Explore all the features from day one."},
  {q:'كيف يتم الدفع؟',a:'الدفع عبر تحويل بنكي. بعد التحويل يتم تفعيل حسابك خلال 24 ساعة.',
   qEn:'How does payment work?',aEn:'Payment is via bank transfer. Your account is activated within 24 hours after transfer.'},
  {q:'كم عدد الموردين في كل باقة؟',a:'الأساسية: 3 موردين، المتوسطة: 10 موردين، المتقدمة: غير محدود.',
   qEn:'How many suppliers per plan?',aEn:'Basic: 3 suppliers, Standard: 10 suppliers, Advanced: unlimited.'},
  {q:'هل يدعم متعدد الفروع؟',a:'نعم — الأساسية: فرع واحد، المتوسطة: 3 فروع، المتقدمة: 10 فروع. وتقدر تضيف فرع لأي باقة بـ 49 ر.س/شهر.',
   qEn:'Does it support multiple branches?',aEn:'Yes — Basic: 1 branch, Standard: 3 branches, Advanced: 10 branches. Extra branches can be added to any plan for 49 SAR/month.'},
  {q:'هل الموظفون يحتاجون تدريب؟',a:'لا — واجهة الموظفين بسيطة جداً بضغطة واحدة، وتدعم 7 لغات لأي جنسية.',
   qEn:'Do staff need training?',aEn:'No — the staff interface is extremely simple (one-tap), and supports 7 languages for any nationality.'},
  {q:'هل يمكن الإلغاء في أي وقت؟',a:'نعم — لا يوجد عقود. يمكنك إلغاء اشتراكك في أي وقت.',
   qEn:'Can I cancel anytime?',aEn:'Yes — no contracts. You can cancel your subscription at any time.'},
]

export const TRUST_POINTS = [
  { icon:'🔒', label:'بياناتك محمية بنسخ احتياطي يومي', labelEn:'Your data is protected with daily backups' },
  { icon:'⚡', label:'إعداد حسابك خلال دقائق', labelEn:'Set up your account in minutes' },
  { icon:'📱', label:'دعم عربي كامل عبر واتساب', labelEn:'Full support via WhatsApp' },
  { icon:'🌍', label:'واجهة موظفين بـ7 لغات', labelEn:'Staff interface in 7 languages' },
]

export const BRANCH_OPTIONS = ['فرع واحد','2-3 فروع','4-10 فروع','أكثر من 10 فروع']
export const BRANCH_OPTIONS_EN = ['1 branch','2-3 branches','4-10 branches','More than 10 branches']

export const FEATURES = [
  { icon:Package, title:'تتبع لحظي', titleEn:'Real-time tracking', desc:'راقب كل صنف في الوقت الحقيقي. كل صرف وكل شراء يُسجَّل فوراً.', descEn:'Monitor every item in real time. Every dispense and purchase is logged instantly.' },
  { icon:MessageCircle, title:'واتساب تلقائي', titleEn:'Automatic WhatsApp alerts', desc:'تنبيه فوري لك وللمورد لما يوصل أي صنف للحد الأدنى.', descEn:'Instant alert to you and your supplier when any item hits its minimum level.' },
  { icon:Users, title:'إدارة الموظفين', titleEn:'Staff management', desc:'كل موظف برمز PIN خاص يصرف من المخزون بدون وصول لبياناتك.', descEn:'Each employee gets a private PIN to dispense stock without access to your data.' },
  { icon:Wallet, title:'إقفال الكاشير اليومي', titleEn:'Daily cashier closing', desc:'تسوية الصندوق بخطوات بسيطة مع صور إثبات، وتنبيه واتساب فوري لك عند أي عجز أو زيادة.', descEn:'Simple cash reconciliation with proof photos, and instant WhatsApp alerts for any shortage or surplus.' },
  { icon:Globe, title:'7 لغات', titleEn:'7 languages', desc:'واجهة موظفين بالعربي والإنجليزي والأردو والهندي والتاغالوغ والبنغالي والفرنسي.', descEn:'Staff interface in Arabic, English, Urdu, Hindi, Tagalog, Bengali, and French.' },
  { icon:BarChart3, title:'تقارير ذكية', titleEn:'Smart reports', desc:'تقارير الصرف والمشتريات والجرد وإقفال الكاشير. صدّرها بـ PDF أو CSV بضغطة واحدة.', descEn:'Dispense, purchase, inventory, and cashier closing reports. Export to PDF or CSV in one click.' },
  { icon:Store, title:'متعدد الفروع', titleEn:'Multi-branch', desc:'أدر جميع فروعك من لوحة تحكم واحدة مع مخزون مستقل لكل فرع.', descEn:'Manage all your branches from one dashboard with independent inventory per branch.' },
  { icon:Bot, title:'أدوات الذكاء الاصطناعي', titleEn:'AI tools', desc:'اقتراح الشراء الذكي بناءً على اتجاه استهلاكك الفعلي، ومقارنة أداء الفروع تلقائياً.', descEn:'Smart purchase suggestions based on your actual consumption trend, and automatic branch performance comparison.' },
  { icon:ShoppingBag, title:'المتجر — حل تقني متكامل', titleEn:'The Store — a complete tech solution', desc:'صفحة عرض منتجات أنيقة برابط أو QR، تشاركها بسهولة مع عملائك — كل شي تحت سقف واحد.', descEn:'An elegant product showcase page via link or QR, easy to share with your customers — all under one roof.', badge:'حل تقني', badgeEn:'Tech Solution' },
]
